### ISSUE TITLE
Milestone one

### ISSUE THREAD

**Issue by mosesbenjamin** [mosesbenjamin/sre-from-local-to-prod#1]
#### Functional Requirement
Using the API we should be able to perform the following operations.
- [x] Add a new student.
- [x] Get all students.
- [x] Get a student with an ID.
- [x] Update existing student information.
- [x] Delete a student record.

#### Expectations
The following expectations should be met to complete this milestone.
- [x] Create a public repository on GitHub.
- [x] The repository should contain the following
README.md file explaining the purpose of the repo, along with local setup instructions.
- [x] Explicitly maintaining dependencies in a file ex (pom.xml, build.gradle, go.mod, requirements.txt, etc).
- [x] Makefile to build and run the REST API locally.
- [x] Ability to run DB schema migrations to create the student table.
- [x] Config (such as database URL) should not be hard-coded in the code and should be passed through environment variables.
- [x] Postman collection for the APIs.
#### API expectations
- [x] Support API versioning (e.g., api/v1/<resource>).
- [x] Using proper HTTP verbs for different operations.
- [x] API should emit meaningful logs with appropriate log levels.
- [x] API should have a /healthcheck endpoint.
- [ ] Unit tests for different endpoints.
